# otel-collector-config.yaml
receivers: # 接收器，用于接收数据
  jaeger: # Jaeger 协议接收器
    protocols: # 定义接收器支持的协议
      thrift_http: # 通过 Jaeger Thrift HTTP 协议接收数据
        endpoint: "0.0.0.0:14278" # 定义 Jaeger Thrift HTTP 接收地址
  otlp: # OpenTelemetry 协议接收器
    protocols: # 定义接收器支持的协议
      grpc: # 通过 gRPC 协议接收数据
        endpoint: 0.0.0.0:4317
      http: # 通过 HTTP 协议接收数据
        endpoint: 0.0.0.0:4318
        cors: # 跨域配置
          allowed_origins: # 允许的域名
            - http://*
            - https://*

exporters: # 导出器，用于导出数据
  jaeger:
    endpoint: "jaeger:14250" # 使用 jaeger 容器名称
    tls:
      insecure: true # 不使用 TLS

  prometheus:
    endpoint: "0.0.0.0:8889" # 这个地址不是Prometheus的地址，而是otel-collector的地址

  logging:
    loglevel: debug

  # otlphttp:
  #   traces_endpoint: "http://192.168.0.102:5080/api/default/traces"
  #   headers:
  #     Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTpyb290MzIx"

processors: # 处理器
  batch: # 批处理配置

service: # 服务配置
  telemetry: # 采集器自身的一些遥测配置
    metrics:
      address: "0.0.0.0:8888" # otel-collector 采集器自身的指标地址
    logs:
      level: "debug" # 日志级别
  pipelines: # 管道配置
    metrics: # 指标管道
      receivers: [otlp] # 接收器
      processors: [] # 处理器
      exporters: [logging, prometheus] # 导出器
    traces: # 链路追踪配置
      receivers: [otlp, jaeger] # 接收器
      exporters: [jaeger] # 导出器
      processors: [batch] # 处理器
